name: Python Linting
description: Run linting using pylint, black, and mypy.
author: Jason Miller

branding:
  icon: check-square
  color: green

inputs:
  pylint_options:
    description: The pylint options to pass to pylint.
    required: false

  black_options:
    description: The black options to pass to black.
    required: false

  mypy_options:
    description: The mypy options to pass to mypy.
    required: false


runs:
  using: composite
  steps:
    - run: pip3 install pylint black mypy
      shell: bash

    - run: pylint ${{ inputs.pylint_optiions }} --reports=y --jobs=0 . 2>&1 | tee pylint_output.txt
      shell: bash
      if: always()


    - run: |
          echo "## Pylint :tada:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo '```text' >> $GITHUB_STEP_SUMMARY
          cat pylint_output.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          rm -f pylint_output.txt
      shell: bash
      if: always()

    - run: black --check ${{ inputs.black_optiions }} . 2>&1 | tee black_output.txt
      shell: bash
      if: always()

    - run: |
          echo "## Black :tada:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo '```text' >> $GITHUB_STEP_SUMMARY
          cat pylint_output.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          rm -f black_output.txt
      shell: bash
      if: always()

    - run: mypy ${{ inputs.mypy_optiions }} . 2>&1 | tee mypy_output.txt
      shell: bash
      if: always()

    - run: |
          echo "## MyPy :tada:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo '```text' >> $GITHUB_STEP_SUMMARY
          cat mypy_output.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          rm -f mypy_output.txt
      shell: bash
      if: always()

    





