name: Python Linting
description: Run linting using pylint, black, and mypy.
author: Jason Miller

branding:
  icon: check-square
  color: green

inputs:
  python-version:
    description: Python version to use for linting. If not specified, uses the default Python available on the runner.
    required: false
    default: '3.x'

  requirements-file:
    description: Path to a requirements file to install before linting. If not specified, only pylint, black, and mypy will be installed.
    required: false
    default: ''

  pylint_options:
    description: The pylint options to pass to pylint.
    required: false

  black_options:
    description: The black options to pass to black.
    required: false

  mypy_options:
    description: The mypy options to pass to mypy.
    required: false

  readme-path:
    description: Path to README.md file to update with badges.
    required: false
    default: 'README.md'

  badge-style:
    description: Badge style - 'url' for GitHub URLs or 'path' for relative paths.
    required: false
    default: 'path'


runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install linting tools
      run: pip3 install pylint black mypy
      shell: bash

    - name: Install additional requirements
      run: |
        if [ -f "${{ inputs.requirements-file }}" ]; then
          pip3 install -r "${{ inputs.requirements-file }}"
        else
          echo "Warning: Requirements file not found: ${{ inputs.requirements-file }}"
          echo "Skipping additional requirements installation."
        fi
      shell: bash
      if: inputs.requirements-file != ''

    - name: Run Pylint
      run: |
        pylint ${{ inputs.pylint_options }} --reports=y --jobs=0 . 2>&1 | tee pylint_output.txt
        echo "PYLINT_EXIT_CODE=$?" >> $GITHUB_ENV
      shell: bash
      if: always()

    - name: Report Pylint results
      run: |
          echo "## Pylint :tada:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo '```text' >> $GITHUB_STEP_SUMMARY
          cat pylint_output.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          rm -f pylint_output.txt
      shell: bash
      if: always()

    - name: Run Black
      run: |
        black --check ${{ inputs.black_options }} . 2>&1 | tee black_output.txt
        echo "BLACK_EXIT_CODE=$?" >> $GITHUB_ENV
      shell: bash
      if: always()

    - name: Report Black results
      run: |
          echo "## Black :tada:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo '```text' >> $GITHUB_STEP_SUMMARY
          cat black_output.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          rm -f black_output.txt
      shell: bash
      if: always()

    - name: Run MyPy
      run: |
        mypy ${{ inputs.mypy_options }} . 2>&1 | tee mypy_output.txt
        echo "MYPY_EXIT_CODE=$?" >> $GITHUB_ENV
      shell: bash
      if: always()

    - name: Report MyPy results
      run: |
          echo "## MyPy :tada:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo '```text' >> $GITHUB_STEP_SUMMARY
          cat mypy_output.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          rm -f mypy_output.txt
      shell: bash
      if: always()

    - name: Generate SVG badges
      run: |
        mkdir -p .github/badges
        
        # Function to create badge
        create_badge() {
          local name=$1
          local status=$2
          local color=$3
          local file=$4
          
          cat > "$file" << 'EOF'
        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="120" height="20">
          <linearGradient id="b" x2="0" y2="100%">
            <stop offset="0" stop-color="#bbb" stop-opacity=".1"/>
            <stop offset="1" stop-opacity=".1"/>
          </linearGradient>
          <clipPath id="a">
            <rect width="120" height="20" rx="3" fill="#fff"/>
          </clipPath>
          <g clip-path="url(#a)">
            <path fill="#555" d="M0 0h60v20H0z"/>
            <path fill="COLOR" d="M60 0h60v20H60z"/>
            <path fill="url(#b)" d="M0 0h120v20H0z"/>
          </g>
          <g fill="#fff" text-anchor="middle" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="11">
            <text x="30" y="15" fill="#010101" fill-opacity=".3">NAME</text>
            <text x="30" y="14">NAME</text>
            <text x="90" y="15" fill="#010101" fill-opacity=".3">STATUS</text>
            <text x="90" y="14">STATUS</text>
          </g>
        </svg>
        EOF
            sed -i "s/NAME/$name/g; s/STATUS/$status/g; s/COLOR/$color/g" "$file"
          }
          
          # Determine badge status based on exit codes
          PYLINT_STATUS="passing"
          PYLINT_COLOR="#4c1"
          [ "${PYLINT_EXIT_CODE:-1}" != "0" ] && PYLINT_STATUS="failing" && PYLINT_COLOR="#e05d44"
          
          BLACK_STATUS="passing"
          BLACK_COLOR="#4c1"
          [ "${BLACK_EXIT_CODE:-1}" != "0" ] && BLACK_STATUS="failing" && BLACK_COLOR="#e05d44"
          
          MYPY_STATUS="passing"
          MYPY_COLOR="#4c1"
          [ "${MYPY_EXIT_CODE:-1}" != "0" ] && MYPY_STATUS="failing" && MYPY_COLOR="#e05d44"
          
          # Create badges for each tool with actual status
          create_badge "pylint" "$PYLINT_STATUS" "$PYLINT_COLOR" ".github/badges/pylint.svg"
          create_badge "black" "$BLACK_STATUS" "$BLACK_COLOR" ".github/badges/black.svg"
          create_badge "mypy" "$MYPY_STATUS" "$MYPY_COLOR" ".github/badges/mypy.svg"
          
          echo "✓ Generated SVG badges in .github/badges/"
        fi
      shell: bash
      if: always()

    - name: Commit badges to repository
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        
        git pull --rebase origin "${{ github.ref_name }}"

        # Add badge files if they exist
        if [ -d ".github/badges" ]; then
          git add .github/badges/pylint.svg || true
          git add .github/badges/black.svg || true
          git add .github/badges/mypy.svg || true
        fi
        
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update linting badges [skip ci]"
          if git push; then
            echo "✓ Changes committed and pushed to repository"
          else
            echo "⚠ Warning: Failed to push changes. This may be due to insufficient permissions or a merge conflict."
            echo "Please ensure the workflow has write permissions to the repository."
            exit 0
          fi
      shell: bash
      if: always()


