name: Python Linting
description: Run linting using pylint, black, and mypy.
author: Jason Miller

branding:
  icon: check-square
  color: green

inputs:
  python-version:
    description: Python version to use for linting. If not specified, uses the default Python available on the runner.
    required: false
    default: '3.x'

  requirements-file:
    description: Path to a requirements file to install before linting. If not specified, only pylint, black, and mypy will be installed.
    required: false
    default: ''

  pylint_options:
    description: The pylint options to pass to pylint.
    required: false

  black_options:
    description: The black options to pass to black.
    required: false

  mypy_options:
    description: The mypy options to pass to mypy.
    required: false

  badge-directory:
    description: Directory to save the generated SVG badges. Defaults to .github/badges.
    required: false
    default: '.github/badges'

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install linting tools
      run: |
        echo "::debug file=action.yml,line=51::Installing pylint, black, and mypy."
        pip3 install pylint black mypy
        if [ $? -eq 0 ]; then
          echo "::notice file=action.yml,line=54::Successfully installed pylint, black, and mypy."
        else
          echo "::error file=action.yml,line=55::Failed to install pylint, black, and mypy."
          exit 1
        fi
      shell: bash

    - name: Install additional requirements
      run: |
        echo "::debug file=action.yml,line=60::Installing additional requirements from ${{ inputs.requirements-file }}"
        if [ -f "${{ inputs.requirements-file }}" ]; then
          pip3 install -r "${{ inputs.requirements-file }}"
          if [ $? -eq 0 ]; then
            echo "::notice file=action.yml,line=62::Successfully installed additional requirements from ${{ inputs.requirements-file }}"
          else
            echo "::error file=action.yml,line=63::Failed to install additional requirements from ${{ inputs.requirements-file }}"
            exit 1
          fi
        else
          echo "::warning file=action.yml,line=63::Requirements file not found: ${{ inputs.requirements-file }}"
          echo "::notice file=action.yml,line=64::Skipping additional requirements installation."
        fi
      shell: bash
      if: inputs.requirements-file != ''

    - name: Run Pylint
      run: |
        echo "::debug file=action.yml,line=67::Running Pylint with options: ${{ inputs.pylint_options }}"
        pylint ${{ inputs.pylint_options }} --reports=y --jobs=0 . 2>&1 | tee pylint_output.txt
        echo "PYLINT_EXIT_CODE=$?" >> $GITHUB_ENV
        echo "::debug file=action.yml,line=71::Pylint completed with exit code ${{ env.PYLINT_EXIT_CODE }}"
      shell: bash
      if: always()

    - name: Report Pylint results
      run: |
          if [ "$PYLINT_EXIT_CODE" == "0" ]; then
            if [ -z "$(cat pylint_output.txt)" ]; then
              echo "::notice file=action.yml,line=70::No linting issues found."
              echo "No linting issues found." > pylint_output.txt
            fi
          else
            if [ -z "$(cat pylint_output.txt)" ]; then
              echo "::warning file=action.yml,line=78::No output from pylint, but exit code indicates issues."
              echo "No output from pylint, but exit code indicates issues." > pylint_output.txt
            else
              echo "::error file=action.yml,line=82::Linting issues found."
            fi
          fi
          echo "::debug file=action.yml,line=75::Reporting Pylint results."
          echo "## Pylint Results :shirt:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo '```text' >> $GITHUB_STEP_SUMMARY
          cat pylint_output.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          rm -f pylint_output.txt
      shell: bash
      if: always()

    - name: Run Black
      run: |
        echo "::debug file=action.yml,line=88::Running Black with options: ${{ inputs.black_options }}"
        black --check ${{ inputs.black_options }} . 2>&1 | tee black_output.txt
        echo "BLACK_EXIT_CODE=$?" >> $GITHUB_ENV
        echo "::debug file=action.yml,line=92::Black completed with exit code ${{ env.BLACK_EXIT_CODE }}"
      shell: bash
      if: always()

    - name: Report Black results
      run: |
          if [ "$BLACK_EXIT_CODE" == "0" ]; then
            if [ -z "$(cat black_output.txt)" ]; then
              echo "::notice file=action.yml,line=97::No code formatting issues found."
              echo "No code formatting issues found." > black_output.txt
            else
              echo "::notice file=action.yml,line=100::Code is properly formatted."
            fi
          else
            if [ -z "$(cat black_output.txt)" ]; then
              echo "::warning file=action.yml,line=105::No output from black, but exit code indicates issues."
              echo "No output from black, but exit code indicates issues." > black_output.txt
            else
              echo "::error file=action.yml,line=93::Code formatting issues found."
            fi
          fi
          echo "::debug file=action.yml,line=90::Reporting Black results."
          echo "## Black Results :art:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo '```text' >> $GITHUB_STEP_SUMMARY
          cat black_output.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "::debug file=action.yml,line=100::Removing temporary black output file."
          rm -f black_output.txt
      shell: bash
      if: always()

    - name: Run MyPy
      run: |
        echo "::debug file=action.yml,line=106::Running MyPy with options: ${{ inputs.mypy_options }}"
        mypy ${{ inputs.mypy_options }} . 2>&1 | tee mypy_output.txt
        echo "MYPY_EXIT_CODE=$?" >> $GITHUB_ENV
        echo "::debug file=action.yml,line=110::MyPy completed with exit code ${{ env.MYPY_EXIT_CODE }}"
      shell: bash
      if: always()

    - name: Report MyPy results
      run: |
          if [ "$MYPY_EXIT_CODE" == "0" ]; then
            if [ -z "$(cat mypy_output.txt)" ]; then
              echo "::notice file=action.yml,line=115::No type checking issues found."
            else
              echo "::warning file=action.yml,line=145::Mypy output present despite zero exit code."
              echo "Mypy output present despite zero exit code." > mypy_output.txt
            fi
            echo "::notice file=action.yml,line=120::All type checks passed."
          else
            echo "::error file=action.yml,line=150::Type checking issues found."
            if [ -z "$(cat mypy_output.txt)" ]; then
              echo "::warning file=action.yml,line=153::No output from mypy, but exit code indicates issues."
            fi
          fi
          echo "## MyPy Results :hammer:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo '```text' >> $GITHUB_STEP_SUMMARY
          cat mypy_output.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "::debug file=action.yml,line=138::Removing temporary mypy output file."
          rm -f mypy_output.txt
      shell: bash
      if: always()

    - name: Generate SVG badges
      run: |
        echo "::debug file=action.yml,line=167::Creating badges directory ${{ inputs.badge-directory }}/ if it does not exist."
        if [ -d "${{ inputs.badge-directory }}" ]; then
          echo "::debug file=action.yml,line=170::Badge directory already exists."
        else
          mkdir -p "${{ inputs.badge-directory }}"
        fi

        # Function to create badge
        create_badge() {
          local name=$1
          local status=$2
          local color=$3
          local file=$4
          
          cat > "$file" << 'EOF'
        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="120" height="20">
          <linearGradient id="b" x2="0" y2="100%">
            <stop offset="0" stop-color="#bbb" stop-opacity=".1"/>
            <stop offset="1" stop-opacity=".1"/>
          </linearGradient>
          <clipPath id="a">
            <rect width="120" height="20" rx="3" fill="#fff"/>
          </clipPath>
          <g clip-path="url(#a)">
            <path fill="#555" d="M0 0h60v20H0z"/>
            <path fill="COLOR" d="M60 0h60v20H60z"/>
            <path fill="url(#b)" d="M0 0h120v20H0z"/>
          </g>
          <g fill="#fff" text-anchor="middle" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="11">
            <text x="30" y="15" fill="#010101" fill-opacity=".3">NAME</text>
            <text x="30" y="14">NAME</text>
            <text x="90" y="15" fill="#010101" fill-opacity=".3">STATUS</text>
            <text x="90" y="14">STATUS</text>
          </g>
        </svg>
        EOF
            sed -i "s/NAME/$name/g; s/STATUS/$status/g; s/COLOR/$color/g" "$file"
          }
          
          # Determine badge status based on exit codes
          PYLINT_STATUS="passing"
          PYLINT_COLOR="#4c1"
          [ "${PYLINT_EXIT_CODE:-1}" != "0" ] && PYLINT_STATUS="failing" && PYLINT_COLOR="#e05d44"
          
          BLACK_STATUS="passing"
          BLACK_COLOR="#4c1"
          [ "${BLACK_EXIT_CODE:-1}" != "0" ] && BLACK_STATUS="failing" && BLACK_COLOR="#e05d44"
          
          MYPY_STATUS="passing"
          MYPY_COLOR="#4c1"
          [ "${MYPY_EXIT_CODE:-1}" != "0" ] && MYPY_STATUS="failing" && MYPY_COLOR="#e05d44"
          
          echo "::debug file=action.yml,line=189::Badge statuses - Pylint: $PYLINT_STATUS, Black: $BLACK_STATUS, MyPy: $MYPY_STATUS"

          # Create badges for each tool with actual status
          create_badge "pylint" "$PYLINT_STATUS" "$PYLINT_COLOR" "${{ inputs.badge-directory }}/pylint.svg"
          create_badge "black" "$BLACK_STATUS" "$BLACK_COLOR" "${{ inputs.badge-directory }}/black.svg"
          create_badge "mypy" "$MYPY_STATUS" "$MYPY_COLOR" "${{ inputs.badge-directory }}/mypy.svg"
          
          echo "::notice file=action.yml,line=195::Generated SVG badges in ${{ inputs.badge-directory }}/"
        fi
      shell: bash
      if: always()

    - name: Commit badges to repository
      run: |
        echo "::debug file=action.yml,line=204::Attempting to commit badge files to repository."
        echo "::notice file=action.yml,line=207::Setting git user email."
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        echo "::notice file=action.yml,line=205::Configuring git user name."
        git config --local user.name "github-actions[bot]"
        
        echo "::debug file=action.yml,line=210::Fetching latest changes from remote and rebasing."
        git pull --rebase origin "${{ github.ref_name }}"

        echo "::notice file=action.yml,line=213::Adding badge files to git staging area."
        # Add badge files if they exist
        echo "::debug file=action.yml,line=216::Adding badge files."
        git add "${{ inputs.badge-directory }}/pylint.svg" || true
        git add "${{ inputs.badge-directory }}/black.svg" || true
        git add "${{ inputs.badge-directory }}/mypy.svg" || true
        
        if git diff --staged --quiet; then
          echo "::notice file=action.yml,line=222::No changes to commit"
        else
          echo "::notice file=action.yml,line=224::Committing and pushing badge changes to repository."
          git commit -m "Update linting badges [skip ci]"
          if git push; then
            echo "::notice file=action.yml,line=227::Changes committed and pushed to repository.
          else
            echo "::warning file=action.yml,line=230::Failed to push changes to repository."
            echo "::notice file=action.yml,line=231::This may be due to insufficient permissions or a merge conflict."
            echo ""
            exit 0
          fi
      shell: bash
      if: always()


