name: Python Linting
description: Run linting using pylint, black, and mypy.
author: Jason Miller

branding:
  icon: check-square
  color: green

inputs:
  python-version:
    description: Python version to use for linting. If not specified, uses the default Python available on the runner.
    required: false
    default: '3.x'

  requirements-file:
    description: Path to a requirements file to install before linting. If not specified, only pylint, black, and mypy will be installed.
    required: false
    default: ''

  pylint_options:
    description: The pylint options to pass to pylint.
    required: false

  black_options:
    description: The black options to pass to black.
    required: false

  mypy_options:
    description: The mypy options to pass to mypy.
    required: false


runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install linting tools
      run: pip3 install pylint black mypy
      shell: bash

    - name: Install additional requirements
      run: |
        if [ -f "${{ inputs.requirements-file }}" ]; then
          pip3 install -r "${{ inputs.requirements-file }}"
        else
          echo "Warning: Requirements file not found: ${{ inputs.requirements-file }}"
          echo "Skipping additional requirements installation."
        fi
      shell: bash
      if: inputs.requirements-file != ''

    - run: pylint ${{ inputs.pylint_options }} --reports=y --jobs=0 . 2>&1 | tee pylint_output.txt
      shell: bash
      if: always()


    - run: |
          echo "## Pylint :tada:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo '```text' >> $GITHUB_STEP_SUMMARY
          cat pylint_output.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          rm -f pylint_output.txt
      shell: bash
      if: always()

    - run: black --check ${{ inputs.black_options }} . 2>&1 | tee black_output.txt
      shell: bash
      if: always()

    - run: |
          echo "## Black :tada:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo '```text' >> $GITHUB_STEP_SUMMARY
          cat black_output.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          rm -f black_output.txt
      shell: bash
      if: always()

    - run: mypy ${{ inputs.mypy_options }} . 2>&1 | tee mypy_output.txt
      shell: bash
      if: always()

    - run: |
          echo "## MyPy :tada:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo '```text' >> $GITHUB_STEP_SUMMARY
          cat mypy_output.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          rm -f mypy_output.txt
      shell: bash
      if: always()

    





