name: Bug Report
description: Report a bug or issue with the Python Linting action
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Configure action with...
        2. Run workflow...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe expected behavior...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe actual behavior...
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Action Version
      description: Which version of the action are you using?
      placeholder: "e.g., v1.2.3 or @main"
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: Which Python version are you using?
      placeholder: "e.g., 3.11"

  - type: input
    id: runner
    attributes:
      label: Runner OS
      description: Which GitHub Actions runner are you using?
      placeholder: "e.g., ubuntu-latest"

  - type: textarea
    id: workflow
    attributes:
      label: Workflow Configuration
      description: Please share the relevant part of your workflow file
      render: yaml
      placeholder: |
        - name: Python Linting
          uses: thoughtparametersllc/python-linting@v1
          with:
            python-version: '3.11'

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Please copy and paste any relevant log output
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
